### ISSUE TITLE
Logos 5 & 6 use wrong font

### ISSUE THREAD

**Issue by twiecki** [pymc-labs/brand#12]
5 & 6 use the font of an older design:
<img width="391" alt="image" src="https://user-images.githubusercontent.com/674200/170834231-a83772e1-5cf3-48c0-b3de-5dfd2f8043b9.png">

We might not have gotten the most recent versions of this but they should be easy to recreate.

**Comment by twiecki** [comment]
I fixed 6. Don't have the tools for 5.

**Comment by OriolAbril** [comment]
Closing as this was fixed with v2 of the logos, the old "logo 5" mentioned above is the "logo 4" of v2 which uses the right font: https://github.com/pymc-labs/brand/blob/main/logos/2022-09-labs-logos-various/04-blue-white.png
